# Generated by Django 4.2.3 on 2023-08-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_checklist_aadhar_card_verification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='Worker_name',
            new_name='worker_name',
        ),
    ]
